M48
; DRILL file {KiCad 9.0.1} date 2025-04-08T10:03:36+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-08T10:03:36+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.900
%
G90
G05
T1
X113.858Y-90.507
X113.858Y-123.527
X134.177Y-90.507
X134.177Y-123.527
M30
